NUMPY it is use to deal with the array (linear algebra fourier transform etc...)

In [12]:
import numpy as np

In [13]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


dealing with the arr in numpy

In [14]:

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


okay so we can create the arr using list tupple or any oth datatype in py

In [15]:

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [16]:
# 0d arr

arr=np.array(42)

# 1d arr

arr1=np.array([1,2,3,4,5])

# 2d arr

arr2=np.array([[1,2,3,4],[5,6,7,8]])

#3d arr
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr1,"\n\n",arr2,"\n\n",arr3)

[1 2 3 4 5] 

 [[1 2 3 4]
 [5 6 7 8]] 

 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [20]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


indexing the array in the numpy

In [25]:

arr=np.array([1,2,3,4,5])

print(arr[1])

2


In [27]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


how to do the slicing 

syntax [start:end:jump_amt]



In [32]:
# the arg are index in it and it go to n-1;

arr = np.array([1, 2, 3, 4])


print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5])

[]
[1 2 3 4]
[2 3]
[2 3 4]
