we can also generate the data base on the given [probablity] dist.


using rand.choice()

In [23]:
import numpy as np

x=np.random.choice([1,2,3,4],p=[.1,.2,.3,.4],size=(10,10))
expr= x==1
x2=x[expr]
print(x2.size)
print(x)


9
[[4 3 4 2 1 3 2 3 3 4]
 [3 3 3 4 3 4 1 4 2 3]
 [3 4 4 3 2 4 4 4 2 4]
 [3 4 3 3 1 1 2 2 2 3]
 [4 4 2 4 3 3 1 1 4 3]
 [2 3 2 1 4 4 3 4 3 3]
 [3 4 4 4 4 2 3 4 2 2]
 [3 4 4 4 3 4 2 2 4 4]
 [3 3 2 3 3 4 3 2 4 1]
 [4 2 2 3 1 3 2 4 3 4]]


In [ ]:
#if the array is present then we can suffel it by using the arr.shuffel()

# while permutation return the new array