random is someting which cannot be predicted..

In [34]:
import numpy as np

print(* (np.random.randint(100) for _ in range(10)))
for num in (np.random.randint(100) for _ in range(10)):
    print(num)

60 28 25 65 52 98 8 16 4 2
44
83
31
80
34
94
5
48
2
24


In [39]:
x=np.random.randint(100,size=(10))

print(x)

x=np.random.randint(10,size=(5,5))

print(x)

[ 8 19 28 86 13 95 72 48 79 11]
[[3 8 6 7 0]
 [4 7 4 5 0]
 [7 1 4 9 2]
 [1 0 8 2 8]
 [8 3 1 1 7]]
